;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq
  ;; Personal information
  user-full-name    "David Janssen"
  user-mail-address "janssen.dhj@gmail.com"

  ;; Set fonts
  doom-font                (font-spec :family "Fira Code" :size 14)
  doom-variable-pitch-font (font-spec :family "Fira Code" :size 14)
  doom-big-font            (font-spec :family "Fira Code" :size 16)

  ;; Allow all themes to be loaded safely
  custom-file        "./.custom.el"
  custom-safe-themes t

  projectile-project-search-path '("~/prj/" "~/opt")

  ;; Turn indentation into something sane
  electric-indent-inhibit   t

  evil-snipe-scope          'whole-visible
  evil-escape-key-sequence  nil

  ;; Configure HTML indentation
  web-mode-markup-indent-offset 2

  browse-url-browser-function #'browse-url-chromium
  )

;; Configure folding
(vimish-fold-global-mode 1) ; Enable persistent folds

;; Configure company-times
(after! company
  (setq company-idle-delay .1
        company-echo-delay .1
        company-minimum-prefix-length 3))

;; Disable global checking
(global-flycheck-mode 'disable)
(add-hook 'prog-mode-hook (lambda () (flyspell-mode-off)))

(load! "my/haskell")
(load! "my/mail")
(load! "my/tasks")

(load! "my/theme") ;; This is autogenerated by my mksys script

;; Be sure this is the last thing we do
(load! "my/map")
